import AppShell from "@/components/layout/app-shell";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  CalendarDays,
  Users,
  ClipboardList,
  CircleCheck,
} from "lucide-react";

const cards = [
  {
    title: "Employees",
    value: "31",
    icon: Users,
  },
  {
    title: "Morning Shift",
    value: "7",
    icon: CalendarDays,
  },
  {
    title: "Afternoon Shift",
    value: "7",
    icon: ClipboardList,
  },
  {
    title: "Roster Status",
    value: "Ready",
    icon: CircleCheck,
  },
];

export default function Home() {
  return (
    <AppShell>
      <div className="space-y-8">
        <div>
          <h2 className="text-3xl font-bold">
            Dashboard
          </h2>

          <p className="text-slate-500">
            Overview of today's operations
          </p>
        </div>

<div className="grid grid-cols-3 gap-6">

  <Card className="col-span-2 p-6">

    <h2 className="text-xl font-semibold mb-5">
      Recent Activity
    </h2>

    <div className="space-y-5">

      <div className="flex justify-between border-b pb-3">
        <div>
          <p className="font-medium">
            July roster generated
          </p>

          <p className="text-sm text-slate-500">
            Automatically generated by the scheduler
          </p>
        </div>

        <Badge>
          Today
        </Badge>
      </div>

      <div className="flex justify-between border-b pb-3">
        <div>
          <p className="font-medium">
            Leave Request
          </p>

          <p className="text-sm text-slate-500">
            Sherzaman Khan requested leave for July 21
          </p>
        </div>

        <Badge variant="secondary">
          Pending
        </Badge>
      </div>

      <div className="flex justify-between border-b pb-3">
        <div>
          <p className="font-medium">
            Queue Updated
          </p>

          <p className="text-sm text-slate-500">
            Voice queue staffing adjusted
          </p>
        </div>

        <Badge variant="outline">
          Auto
        </Badge>
      </div>

    </div>

  </Card>

  <Card className="p-6">

    <h2 className="text-xl font-semibold">
      Quick Stats
    </h2>

    <div className="space-y-5 mt-6">

      <div>

        <p className="text-slate-500">
          L1 Analysts
        </p>

        <p className="text-3xl font-bold">
          16
        </p>

      </div>

      <div>

        <p className="text-slate-500">
          L2 Analysts
        </p>

        <p className="text-3xl font-bold">
          15
        </p>

      </div>

      <div>

        <p className="text-slate-500">
          Leave Requests
        </p>

        <p className="text-3xl font-bold">
          2
        </p>

      </div>

      <div>

        <p className="text-slate-500">
          Queue Health
        </p>

        <Badge>
          Excellent
        </Badge>

      </div>

    </div>

  </Card>
</div>
</div>
    </AppShell>
  );
}